"""empty message

Revision ID: b9d0a0a91787
Revises: 
Create Date: 2025-01-25 16:13:12.803817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9d0a0a91787'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archive_data', sa.Column('slip_type', sa.String(), nullable=False))
    op.add_column('health_data', sa.Column('slip_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('health_data', 'slip_type')
    op.drop_column('archive_data', 'slip_type')
    # ### end Alembic commands ###
